kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: petclinic
  labels:
    app.kubernetes.io/name: petclinic
    app.kubernetes.io/component: webapp
    app.kubernetes.io/part-of: petclinic
spec:
  backend:
    serviceName: petclinic
    servicePort: 8080